server:
  port: 8081
spring:
  application:
    name: x
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/x_db?useSSL=false&serverTimezone=UTC
    username: root
    password: maijiajun666
  redis:
    host: 192.168.159.128
    port: 6379

mybatis-plus:
  type-aliases-package: xyz.ivan.x.entity # 别名扫描包