server:
  port: 8081
spring:
  application:
    name: x
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/x_db?useSSL=false&serverTimezone=UTC
    username: root
    password: maijiajun666

mybatis-plus:
  type-aliases-package: xyz.ivan.x.entity # 别名扫描包